id: P27480819
initial_creation_type: ocr
source_metadata:
  volumes:
    65fea8cc6213440d9de59aea82647feb:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཕགས་མ་ལྷ་མོ་སྒྲོལ་མ་ལ་བསྟོད་པ།
      total_pages: 1648
      volume_number: 40
